name: WideWorldImporters-DWH

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_source
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - dwh_network

  postgres_source:
    image: postgres:15
    container_name: postgres_source
    environment:
      POSTGRES_USER: ${POSTGRES_SOURCE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SOURCE_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_source_data:/var/lib/postgresql/data
    networks:
      - dwh_network

  postgres_dwh:
    image: postgres:15
    container_name: postgres_dwh
    environment:
      POSTGRES_USER: ${POSTGRES_DWH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DWH_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DWH_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres_dwh_data:/var/lib/postgresql/data
    networks:
      - dwh_network

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    depends_on:
      - postgres_dwh

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_DWH_USER}:${POSTGRES_DWH_PASSWORD}@postgres_dwh/${POSTGRES_DWH_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: "/opt/airflow"
    ports:
      - "8080:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl

    networks:
      - dwh_network

    command: standalone

volumes:
  mssql_data:
  postgres_source_data:
  postgres_dwh_data:

networks:
  dwh_network:
    driver: bridge